apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: search-graphql
  description: GraphQL API for the VTEX store APIs, providing search functionality and resolvers for catalog and orders
  annotations:
    github.com/project-slug: vtex-apps/search-graphql
    vtex.com/platform-flow-id: Shopper#1
spec:
  type: service
  lifecycle: production
  owner: search-engagement-team
