export const getProduct = (customFields = {}) => {
  return {
    cacheId: 'classic-shoes',
    productId: '16',
    productName: 'Classic Shoes Top',
    brand: 'Mizuno',
    brandId: 2000010,
    brandImageUrl: null,
    linkText: 'classic-shoes',
    productReference: '12531',
    categoryId: '10',
    productTitle: 'Classic Shoes',
    metaTagDescription: "If you go classic, you can't go wrong.",
    clusterHighlights: {},
    productClusters: {},
    searchableClusters: {},
    categories: ['/Apparel & Accessories/Shoes/', '/Apparel & Accessories/'],
    categoriesIds: ['/25/10/', '/25/'],
    link: 'https://storecomponents.vtexcommercestable.com.br/classic-shoes/p',
    'Numero do calçado': ['35'],
    Tamanho: ['Numero do calçado'],
    allSpecifications: ['Numero do calçado'],
    allSpecificationsGroups: ['Tamanho'],
    description: "If you go classic, you can't go wrong.",
    items: [
      {
        itemId: '35',
        name: 'Classic Pink',
        nameComplete: 'Classic Shoes Top Classic Pink',
        complementName:
          'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
        ean: '80098',
        referenceId: [
          {
            Key: 'RefId',
            Value: '12531',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: '155470',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155470-#width#-#height#/Frame-11.jpg?v=636793763155730000" width="#width#" height="#height#" alt="Frame-11" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155470/Frame-11.jpg?v=636793763155730000',
            imageText: 'Frame-11',
          },
          {
            imageId: '155471',
            imageLabel: 'hover',
            imageTag:
              '<img src="~/arquivos/ids/155471-#width#-#height#/Frame-10.jpg?v=637018188181300000" width="#width#" height="#height#" alt="Frame lala Á" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155471/Frame-10.jpg?v=637018188181300000',
            imageText: 'Frame lala Á',
          },
          {
            imageId: '155559',
            imageLabel: 'PinkSKUVariation',
            imageTag:
              '<img src="~/arquivos/ids/155559-#width#-#height#/pink-sku-variation.png?v=637063238989370000" width="#width#" height="#height#" alt="Pink-SKU-Variation" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155559/pink-sku-variation.png?v=637063238989370000',
            imageText: 'Pink-SKU-Variation',
          },
        ],
        Tamanho: ['40'],
        Cor: ['Verde'],
        variations: ['Tamanho', 'Cor'],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://storecomponents.vtexcommercestable.com.br/checkout/cart/add?sku=35&qty=1&seller=1&sc=1&price=3890&cv=d7dfda620290c1bbf7547535348be747_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                '0': {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'American Express',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'American Express à vista',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa à vista',
                },
                {
                  Value: 19.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 2 vezes sem juros',
                },
                {
                  Value: 13,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 3 vezes sem juros',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard à vista',
                },
                {
                  Value: 19.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 2 vezes sem juros',
                },
                {
                  Value: 13,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 3 vezes sem juros',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Boleto Bancário',
                  PaymentSystemGroupName: 'bankInvoicePaymentGroup',
                  Name: 'Boleto Bancário à vista',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Promissory',
                  PaymentSystemGroupName: 'promissoryPaymentGroup',
                  Name: 'Promissory à vista',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit à vista',
                },
                {
                  Value: 19.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 2 vezes sem juros',
                },
                {
                  Value: 13,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 3 vezes sem juros',
                },
                {
                  Value: 38.9,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 38.9,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Free',
                  PaymentSystemGroupName: 'custom201PaymentGroupPaymentGroup',
                  Name: 'Free à vista',
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 38.9,
              ListPrice: 38.9,
              PriceWithoutDiscount: 38.9,
              RewardValue: 0,
              PriceValidUntil: '2020-10-13T12:55:24.2214801Z',
              AvailableQuantity: 2000000,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                'd7dfda620290c1bbf7547535348be747_',
            },
          },
        ],
        Videos: [],
      },
      {
        itemId: '36',
        name: 'White Slip On',
        nameComplete: 'Classic Shoes Top White Slip On',
        complementName:
          'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
        ean: '80099',
        referenceId: [
          {
            Key: 'RefId',
            Value: '12532',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: '155472',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155472-#width#-#height#/Frame-3.jpg?v=636793763985400000" width="#width#" height="#height#" alt="Frame-3" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155472/Frame-3.jpg?v=636793763985400000',
            imageText: 'Frame-3',
          },
          {
            imageId: '155473',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155473-#width#-#height#/Frame.jpg?v=636793764101900000" width="#width#" height="#height#" alt="Frame" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155473/Frame.jpg?v=636793764101900000',
            imageText: 'Frame',
          },
          {
            imageId: '155561',
            imageLabel: 'WhiteSKUVariation',
            imageTag:
              '<img src="~/arquivos/ids/155561-#width#-#height#/white-sku-variation.png?v=637063306978570000" width="#width#" height="#height#" alt="White-SKU-Variation" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155561/white-sku-variation.png?v=637063306978570000',
            imageText: 'White-SKU-Variation',
          },
        ],
        Tamanho: ['41'],
        Cor: ['Cinza'],
        variations: ['Tamanho', 'Cor'],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://storecomponents.vtexcommercestable.com.br/checkout/cart/add?sku=36&qty=1&seller=1&sc=1&price=26250&cv=d7dfda620290c1bbf7547535348be747_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                '0': {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'American Express',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'American Express à vista',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa à vista',
                },
                {
                  Value: 131.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 2 vezes sem juros',
                },
                {
                  Value: 87.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 3 vezes sem juros',
                },
                {
                  Value: 65.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 4,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 4 vezes sem juros',
                },
                {
                  Value: 52.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 5,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 5 vezes sem juros',
                },
                {
                  Value: 43.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 6,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa 6 vezes sem juros',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard à vista',
                },
                {
                  Value: 131.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 2 vezes sem juros',
                },
                {
                  Value: 87.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 3 vezes sem juros',
                },
                {
                  Value: 65.7,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 4,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 4 vezes sem juros',
                },
                {
                  Value: 52.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 5,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 5 vezes sem juros',
                },
                {
                  Value: 43.8,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 6,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard 6 vezes sem juros',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Boleto Bancário',
                  PaymentSystemGroupName: 'bankInvoicePaymentGroup',
                  Name: 'Boleto Bancário à vista',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Promissory',
                  PaymentSystemGroupName: 'promissoryPaymentGroup',
                  Name: 'Promissory à vista',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit à vista',
                },
                {
                  Value: 131.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 2 vezes sem juros',
                },
                {
                  Value: 87.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 3 vezes sem juros',
                },
                {
                  Value: 262.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 262.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Free',
                  PaymentSystemGroupName: 'custom201PaymentGroupPaymentGroup',
                  Name: 'Free à vista',
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 262.5,
              ListPrice: 262.5,
              PriceWithoutDiscount: 262.5,
              RewardValue: 0,
              PriceValidUntil: '2020-10-13T12:55:24.2710554Z',
              AvailableQuantity: 2000000,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                'd7dfda620290c1bbf7547535348be747_',
            },
          },
        ],
        Videos: [],
      },
      {
        itemId: '37',
        name: 'Cool Pink',
        nameComplete: 'Classic Shoes Top Cool Pink',
        complementName:
          'Os corredores de alta performance terão um grande aliado com o Tênis Mizuno Wave Viper 3 Masculino. A placa Wave de ponta a ponta garante um amortecimento responsivo do começo ao fim da corrida.',
        ean: '80100',
        referenceId: [
          {
            Key: 'RefId',
            Value: '12533',
          },
        ],
        measurementUnit: 'un',
        unitMultiplier: 1,
        modalType: null,
        isKit: false,
        images: [
          {
            imageId: '155474',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155474-#width#-#height#/Frame-1.jpg?v=636793764631500000" width="#width#" height="#height#" alt="Frame-1" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155474/Frame-1.jpg?v=636793764631500000',
            imageText: 'Frame-1',
          },
          {
            imageId: '155475',
            imageLabel: '',
            imageTag:
              '<img src="~/arquivos/ids/155475-#width#-#height#/Frame-2.jpg?v=636793764763600000" width="#width#" height="#height#" alt="Frame-2" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155475/Frame-2.jpg?v=636793764763600000',
            imageText: 'Frame-2',
          },
          {
            imageId: '155560',
            imageLabel: 'PinkCoolSKUVariation',
            imageTag:
              '<img src="~/arquivos/ids/155560-#width#-#height#/pink-cool-sku-variation.png?v=637063239809000000" width="#width#" height="#height#" alt="Pink-Cool-SKU-Variation" id="" />',
            imageUrl:
              'http://storecomponents.vteximg.com.br/arquivos/ids/155560/pink-cool-sku-variation.png?v=637063239809000000',
            imageText: 'Pink-Cool-SKU-Variation',
          },
        ],
        Tamanho: ['42'],
        Cor: ['Vermelho'],
        variations: ['Tamanho', 'Cor'],
        sellers: [
          {
            sellerId: '1',
            sellerName: 'VTEX',
            addToCartLink:
              'https://storecomponents.vtexcommercestable.com.br/checkout/cart/add?sku=37&qty=1&seller=1&sc=1&price=1050&cv=d7dfda620290c1bbf7547535348be747_&sc=1',
            sellerDefault: true,
            commertialOffer: {
              DeliverySlaSamplesPerRegion: {
                '0': {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              },
              Installments: [
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'American Express',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'American Express à vista',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Visa',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Visa à vista',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Mastercard',
                  PaymentSystemGroupName: 'creditCardPaymentGroup',
                  Name: 'Mastercard à vista',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Boleto Bancário',
                  PaymentSystemGroupName: 'bankInvoicePaymentGroup',
                  Name: 'Boleto Bancário à vista',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Promissory',
                  PaymentSystemGroupName: 'promissoryPaymentGroup',
                  Name: 'Promissory à vista',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit à vista',
                },
                {
                  Value: 5.3,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 2,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 2 vezes sem juros',
                },
                {
                  Value: 3.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 3,
                  PaymentSystemName: 'Customer Credit',
                  PaymentSystemGroupName: 'creditControlPaymentGroup',
                  Name: 'Customer Credit 3 vezes sem juros',
                },
                {
                  Value: 10.5,
                  InterestRate: 0,
                  TotalValuePlusInterestRate: 10.5,
                  NumberOfInstallments: 1,
                  PaymentSystemName: 'Free',
                  PaymentSystemGroupName: 'custom201PaymentGroupPaymentGroup',
                  Name: 'Free à vista',
                },
              ],
              DiscountHighLight: [],
              GiftSkuIds: [],
              Teasers: [],
              BuyTogether: [],
              ItemMetadataAttachment: [],
              Price: 10.5,
              ListPrice: 10.5,
              PriceWithoutDiscount: 10.5,
              RewardValue: 0,
              PriceValidUntil: '2020-10-13T12:55:24.3541901Z',
              AvailableQuantity: 1000000,
              Tax: 0,
              DeliverySlaSamples: [
                {
                  DeliverySlaPerTypes: [],
                  Region: null,
                },
              ],
              GetInfoErrorMessage: null,
              CacheVersionUsedToCallCheckout:
                'd7dfda620290c1bbf7547535348be747_',
            },
          },
        ],
        Videos: [],
      },
    ],
    ...customFields,
  }
}
export const getItem = (
  id = '1',
  price = 90,
  quantity = 10,
  customFields = {}
) => {
  return {
    itemId: id,
    name: `Item ${id}`,
    nameComplete: `Name ${id} Complete`,
    images: [
      {
        imageId: id,
        imageLabel: `${id}-Color`,
        imageTag: 'imageTag',
        imageUrl: 'imageurl.com',
        imageText: 'imageText',
      },
    ],
    sellers: [
      {
        sellerId: id,
        sellerName: 'Store Name',
        commertialOffer: {
          AvailableQuantity: quantity,
          ListPrice: price + 10,
          Price: price,
        },
      },
    ],
    ...customFields,
  }
}
